# Config file for automatic testing at travis-ci.org
language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"

env:
  - DJANGO=https://github.com/django/django/archive/master.tar.gz
  - DJANGO=django>=1.6
  - DJANGO=django>=1.5.5

install:
  - pip install $DJANGO
  - pip install -r requirements-test.txt --use-mirrors

script:
  - coverage run --source periodicals runtests.py
  - coverage report

matrix:
  exclude:
    - python: "3.3"
      env: DJANGO=django==1.4.10
    - python: "2.6"
      env: DJANGO=https://github.com/django/django/archive/master.tar.gz
